version:  '3.7'
services:
  jupyter-base-notebook:
      image: jupyterdatascienceimage
      ports:
      - 8888:8888
      environment:
        JUPYTER_TOKEN: "docker"
      volumes:
        - ./:/home/jovyan/work
        - ./jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py
        - ./jupyter_server_config.py:/etc/jupyter/jupyter_server_config.py
  
      container_name:  jupyterdatasciencecontainer